compute_environment: LOCAL_MACHINE
deepspeed_config:
 deepspeed_config_file: /home/hk-project-test-lmcdm/ew9122/training/Truthfulness_Study_Hug/configs/zero2_config_accelerate.json
 zero3_init_flag: false
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
use_cpu: false
